name: inception

services:
  nginx:
    image: nginx:inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443/tcp"
    networks:
      - inception
    secrets:
      - ssl.crt
      - ssl.key

#  WordPress:
#    volumes:
#      - type: bind
#        source: ${HOME}/data/web
#        target: /web
#        read_only: true
#  MariaDB:
#    volumes:
#      - type: bind
#        source: ${HOME}/data/db
#        target: /db
#        read_only: false
#
networks:
  inception: {} 

secrets:
  ssl.crt:
    file: ./requirements/nginx/conf/ssl.crt
  ssl.key:
    file: ./requirements/nginx/conf/ssl.key
