name: inception

services:
  nginx:
    image: nginx:inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443/tcp"
    networks:
      - inception
    secrets:
      - ssl.crt
      - ssl.key
    volumes:
      - type: bind
        source: ${HOME}/data/web
        target: /var/www/wp
        read_only: true
    restart: on-failure

  wordpress:
    image: wordpress:inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - type: bind
        source: ${HOME}/data/web
        target: /web
#        read_only: true
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password
      - MARIADB_HOST=${MARIADB_HOST}
      - WP_CREDENTIALS_FILE=/run/secrets/credentials
    secrets:
      - db_root_password
      - db_password
      - credentials
    restart: on-failure

  mariadb:
    image: mariadb:inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
#############################################
# ___DESCOMENTAR PARA PRUEBAS.___
# En producción el entrypoint solo es nginx
#    ports:
#      - "3306:3306/tcp"
#############################################
    networks:
      - inception
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    restart: on-failure
    volumes:
      - type: bind
        source: ${HOME}/data/db
        target: /usr/local/mysql/var
        read_only: false

networks:
  inception: {} 

secrets:
  ssl.crt:
    file: ../secrets/ssl.crt
  ssl.key:
    file: ../secrets/ssl.key
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt
