name: inception

services:
  nginx:
    image: nginx:inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443/tcp"
    networks:
      - inception
    secrets:
      - ssl.crt
      - ssl.key
    volumes:
      - type: bind
        source: ${HOME}/data/web
        target: /var/www/wp
        read_only: true
    restart: always

  wordpress:
    image: wordpress:inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    volumes:
      - type: bind
        source: ${HOME}/data/web
        target: /web
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password
      - MARIADB_HOST=${MARIADB_HOST}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD_FILE=/run/secrets/wp_user_password
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    restart: always

  mariadb:
    image: mariadb:inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping"]
      start_period: 5s
      interval: 2s
      retries: 6
#############################################
# ___DESCOMENTAR PARA PRUEBAS.___
# En producción el entrypoint solo es nginx
#    ports:
#      - "3306:3306/tcp"
#############################################
    networks:
      - inception
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    restart: always
    volumes:
      - type: bind
        source: ${HOME}/data/db
        target: /usr/local/mysql/var
        read_only: false

networks:
  inception: {} 

secrets:
  ssl.crt:
    file: ../secrets/ssl.crt
  ssl.key:
    file: ../secrets/ssl.key
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
